enum actionTypes {
  PUSH = 'ARRAY_PUSH',
  POP = 'ARRAY_POP',
  INSERT = 'ARRAY_INSERT',
  UPDATE = 'ARRAY_UPDATE',
  SET = 'ARRAY_SET',
  DELETE = 'ARRAY_DELETE',
  DELETE_WHERE = 'ARRAY_DELETE_WHERE',
  EMPTY = 'ARRAY_EMPTY',
  SWAP = 'ARRAY_SWAP',
}

export default actionTypes;
